// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
	"saas/biz/dal/casbin"
	"saas/biz/handler/mw"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetJWTMw(casbin.CasbinEnforcer()).MiddlewareFunc(),
		mw.LogMw(),
	}
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderlistexportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderallcountMw() []app.HandlerFunc {
	// your code...
	return nil
}
