version: '3'

services:

  #golang 服务
  golang:
    hostname: golang
#    image: golang:latest  # 父镜像名称
    image: golang:1.23.4
    volumes: # 挂载卷
      - /xingfufit/go:/go
    ports: # 端口映射
      - "9039:9039"
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    # command: 启动后运行的命令
#    profiles:
#      - dev
#      - release

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: Yj123987
      MINIO_SECRET_KEY: Yj987123
    volumes:
      - /xingfufit/go/minio/:/data
      - /xingfufit/go/minio/:/root/.minio
    command: server --console-address ':9001' /data
    privileged: true
    restart: always
#    profiles:
#      - dev
#      - release