version: '3'

services:

  #golang 服务
  golang:
    hostname: golang
    #image: golang:latest  # 父镜像名称
    image: golang:1.21.4
    volumes: # 挂载卷
      - /D/docker/go-project:/go
    ports: # 端口映射
      - "9039:9039"
    stdin_open: true
    tty: true
    # command: 启动后运行的命令

  minio:
    image: minio/minio
    container_name: saas_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: douyin
      MINIO_SECRET_KEY: douyin123
    volumes:
      - /D/docker/src/my-saas-basics/files/minio/:/data
      - /D/docker/src/my-saas-basics/files/minio/:/root/.minio
    command: server --console-address ':9001' /data
    privileged: true
    restart: always
    profiles:
      - dev
      - release