Name: Kcersing Admin
IsProd: true
Host: 0.0.0.0
Port: 9039
Timeout: 30000

Captcha:
  KeyLong: 5
  ImgWidth: 240
  ImgHeight: 80

Auth:
  OAuthKey: OauthJf3z1n2xxx2cr1
  AccessSecret: D86VKDtsJf3z1nxxxxtsJf3z1n5
  AccessExpire: 259200 # seconds, 3 days

Redis:
  Host: 127.0.0.1
  Port: 6379
  Type: node
MySql:
  Host: root:root@tcp(127.0.0.1:3306)/saas?charset=utf8&parseTime=True&loc=Local
  Salt: YOUR_SALT

Casbin:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

# 支付平台信息配置
Payment:
  Wechat:
    appid: wx1234567890
    mch_id:
    api_key:
    api_v3_key:
    cert_file_content:
    key_file_content:
    pkcs12_file_content:
  Alipay: # 以下配置文件为新沙箱环境配置
    appid:
    private_key:
    app_public_cert_content:
    alipay_root_cert_content:
    alipay_public_cert_content:

Minio:
  EndPoint : localhost:9000
  AccessKeyID : douyin
  SecretAccessKey : douyin123
  UseSSL : false
  VideoBucketName : videobucket
  ImgBucketName : imagebucket
  Url : http://localhost:9000