// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"saas/pkg/db/ent/courserecordcoach"
	"saas/pkg/db/ent/courserecordschedule"
	"saas/pkg/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseRecordCoachQuery is the builder for querying CourseRecordCoach entities.
type CourseRecordCoachQuery struct {
	config
	ctx          *QueryContext
	order        []courserecordcoach.OrderOption
	inters       []Interceptor
	predicates   []predicate.CourseRecordCoach
	withSchedule *CourseRecordScheduleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CourseRecordCoachQuery builder.
func (crcq *CourseRecordCoachQuery) Where(ps ...predicate.CourseRecordCoach) *CourseRecordCoachQuery {
	crcq.predicates = append(crcq.predicates, ps...)
	return crcq
}

// Limit the number of records to be returned by this query.
func (crcq *CourseRecordCoachQuery) Limit(limit int) *CourseRecordCoachQuery {
	crcq.ctx.Limit = &limit
	return crcq
}

// Offset to start from.
func (crcq *CourseRecordCoachQuery) Offset(offset int) *CourseRecordCoachQuery {
	crcq.ctx.Offset = &offset
	return crcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crcq *CourseRecordCoachQuery) Unique(unique bool) *CourseRecordCoachQuery {
	crcq.ctx.Unique = &unique
	return crcq
}

// Order specifies how the records should be ordered.
func (crcq *CourseRecordCoachQuery) Order(o ...courserecordcoach.OrderOption) *CourseRecordCoachQuery {
	crcq.order = append(crcq.order, o...)
	return crcq
}

// QuerySchedule chains the current query on the "schedule" edge.
func (crcq *CourseRecordCoachQuery) QuerySchedule() *CourseRecordScheduleQuery {
	query := (&CourseRecordScheduleClient{config: crcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(courserecordcoach.Table, courserecordcoach.FieldID, selector),
			sqlgraph.To(courserecordschedule.Table, courserecordschedule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, courserecordcoach.ScheduleTable, courserecordcoach.ScheduleColumn),
		)
		fromU = sqlgraph.SetNeighbors(crcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CourseRecordCoach entity from the query.
// Returns a *NotFoundError when no CourseRecordCoach was found.
func (crcq *CourseRecordCoachQuery) First(ctx context.Context) (*CourseRecordCoach, error) {
	nodes, err := crcq.Limit(1).All(setContextOp(ctx, crcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{courserecordcoach.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) FirstX(ctx context.Context) *CourseRecordCoach {
	node, err := crcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CourseRecordCoach ID from the query.
// Returns a *NotFoundError when no CourseRecordCoach ID was found.
func (crcq *CourseRecordCoachQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = crcq.Limit(1).IDs(setContextOp(ctx, crcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{courserecordcoach.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) FirstIDX(ctx context.Context) int64 {
	id, err := crcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CourseRecordCoach entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CourseRecordCoach entity is found.
// Returns a *NotFoundError when no CourseRecordCoach entities are found.
func (crcq *CourseRecordCoachQuery) Only(ctx context.Context) (*CourseRecordCoach, error) {
	nodes, err := crcq.Limit(2).All(setContextOp(ctx, crcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{courserecordcoach.Label}
	default:
		return nil, &NotSingularError{courserecordcoach.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) OnlyX(ctx context.Context) *CourseRecordCoach {
	node, err := crcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CourseRecordCoach ID in the query.
// Returns a *NotSingularError when more than one CourseRecordCoach ID is found.
// Returns a *NotFoundError when no entities are found.
func (crcq *CourseRecordCoachQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = crcq.Limit(2).IDs(setContextOp(ctx, crcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{courserecordcoach.Label}
	default:
		err = &NotSingularError{courserecordcoach.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := crcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CourseRecordCoaches.
func (crcq *CourseRecordCoachQuery) All(ctx context.Context) ([]*CourseRecordCoach, error) {
	ctx = setContextOp(ctx, crcq.ctx, "All")
	if err := crcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CourseRecordCoach, *CourseRecordCoachQuery]()
	return withInterceptors[[]*CourseRecordCoach](ctx, crcq, qr, crcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) AllX(ctx context.Context) []*CourseRecordCoach {
	nodes, err := crcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CourseRecordCoach IDs.
func (crcq *CourseRecordCoachQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if crcq.ctx.Unique == nil && crcq.path != nil {
		crcq.Unique(true)
	}
	ctx = setContextOp(ctx, crcq.ctx, "IDs")
	if err = crcq.Select(courserecordcoach.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) IDsX(ctx context.Context) []int64 {
	ids, err := crcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crcq *CourseRecordCoachQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crcq.ctx, "Count")
	if err := crcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crcq, querierCount[*CourseRecordCoachQuery](), crcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) CountX(ctx context.Context) int {
	count, err := crcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crcq *CourseRecordCoachQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crcq.ctx, "Exist")
	switch _, err := crcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crcq *CourseRecordCoachQuery) ExistX(ctx context.Context) bool {
	exist, err := crcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CourseRecordCoachQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crcq *CourseRecordCoachQuery) Clone() *CourseRecordCoachQuery {
	if crcq == nil {
		return nil
	}
	return &CourseRecordCoachQuery{
		config:       crcq.config,
		ctx:          crcq.ctx.Clone(),
		order:        append([]courserecordcoach.OrderOption{}, crcq.order...),
		inters:       append([]Interceptor{}, crcq.inters...),
		predicates:   append([]predicate.CourseRecordCoach{}, crcq.predicates...),
		withSchedule: crcq.withSchedule.Clone(),
		// clone intermediate query.
		sql:  crcq.sql.Clone(),
		path: crcq.path,
	}
}

// WithSchedule tells the query-builder to eager-load the nodes that are connected to
// the "schedule" edge. The optional arguments are used to configure the query builder of the edge.
func (crcq *CourseRecordCoachQuery) WithSchedule(opts ...func(*CourseRecordScheduleQuery)) *CourseRecordCoachQuery {
	query := (&CourseRecordScheduleClient{config: crcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crcq.withSchedule = query
	return crcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CourseRecordCoach.Query().
//		GroupBy(courserecordcoach.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crcq *CourseRecordCoachQuery) GroupBy(field string, fields ...string) *CourseRecordCoachGroupBy {
	crcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CourseRecordCoachGroupBy{build: crcq}
	grbuild.flds = &crcq.ctx.Fields
	grbuild.label = courserecordcoach.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CourseRecordCoach.Query().
//		Select(courserecordcoach.FieldCreatedAt).
//		Scan(ctx, &v)
func (crcq *CourseRecordCoachQuery) Select(fields ...string) *CourseRecordCoachSelect {
	crcq.ctx.Fields = append(crcq.ctx.Fields, fields...)
	sbuild := &CourseRecordCoachSelect{CourseRecordCoachQuery: crcq}
	sbuild.label = courserecordcoach.Label
	sbuild.flds, sbuild.scan = &crcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CourseRecordCoachSelect configured with the given aggregations.
func (crcq *CourseRecordCoachQuery) Aggregate(fns ...AggregateFunc) *CourseRecordCoachSelect {
	return crcq.Select().Aggregate(fns...)
}

func (crcq *CourseRecordCoachQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crcq); err != nil {
				return err
			}
		}
	}
	for _, f := range crcq.ctx.Fields {
		if !courserecordcoach.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crcq.path != nil {
		prev, err := crcq.path(ctx)
		if err != nil {
			return err
		}
		crcq.sql = prev
	}
	return nil
}

func (crcq *CourseRecordCoachQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CourseRecordCoach, error) {
	var (
		nodes       = []*CourseRecordCoach{}
		_spec       = crcq.querySpec()
		loadedTypes = [1]bool{
			crcq.withSchedule != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CourseRecordCoach).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CourseRecordCoach{config: crcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crcq.withSchedule; query != nil {
		if err := crcq.loadSchedule(ctx, query, nodes, nil,
			func(n *CourseRecordCoach, e *CourseRecordSchedule) { n.Edges.Schedule = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crcq *CourseRecordCoachQuery) loadSchedule(ctx context.Context, query *CourseRecordScheduleQuery, nodes []*CourseRecordCoach, init func(*CourseRecordCoach), assign func(*CourseRecordCoach, *CourseRecordSchedule)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CourseRecordCoach)
	for i := range nodes {
		fk := nodes[i].CourseRecordScheduleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(courserecordschedule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_record_schedule_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crcq *CourseRecordCoachQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crcq.querySpec()
	_spec.Node.Columns = crcq.ctx.Fields
	if len(crcq.ctx.Fields) > 0 {
		_spec.Unique = crcq.ctx.Unique != nil && *crcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crcq.driver, _spec)
}

func (crcq *CourseRecordCoachQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(courserecordcoach.Table, courserecordcoach.Columns, sqlgraph.NewFieldSpec(courserecordcoach.FieldID, field.TypeInt64))
	_spec.From = crcq.sql
	if unique := crcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crcq.path != nil {
		_spec.Unique = true
	}
	if fields := crcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, courserecordcoach.FieldID)
		for i := range fields {
			if fields[i] != courserecordcoach.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crcq.withSchedule != nil {
			_spec.Node.AddColumnOnce(courserecordcoach.FieldCourseRecordScheduleID)
		}
	}
	if ps := crcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crcq *CourseRecordCoachQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crcq.driver.Dialect())
	t1 := builder.Table(courserecordcoach.Table)
	columns := crcq.ctx.Fields
	if len(columns) == 0 {
		columns = courserecordcoach.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crcq.sql != nil {
		selector = crcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crcq.ctx.Unique != nil && *crcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crcq.predicates {
		p(selector)
	}
	for _, p := range crcq.order {
		p(selector)
	}
	if offset := crcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CourseRecordCoachGroupBy is the group-by builder for CourseRecordCoach entities.
type CourseRecordCoachGroupBy struct {
	selector
	build *CourseRecordCoachQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crcgb *CourseRecordCoachGroupBy) Aggregate(fns ...AggregateFunc) *CourseRecordCoachGroupBy {
	crcgb.fns = append(crcgb.fns, fns...)
	return crcgb
}

// Scan applies the selector query and scans the result into the given value.
func (crcgb *CourseRecordCoachGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crcgb.build.ctx, "GroupBy")
	if err := crcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CourseRecordCoachQuery, *CourseRecordCoachGroupBy](ctx, crcgb.build, crcgb, crcgb.build.inters, v)
}

func (crcgb *CourseRecordCoachGroupBy) sqlScan(ctx context.Context, root *CourseRecordCoachQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crcgb.fns))
	for _, fn := range crcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crcgb.flds)+len(crcgb.fns))
		for _, f := range *crcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CourseRecordCoachSelect is the builder for selecting fields of CourseRecordCoach entities.
type CourseRecordCoachSelect struct {
	*CourseRecordCoachQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crcs *CourseRecordCoachSelect) Aggregate(fns ...AggregateFunc) *CourseRecordCoachSelect {
	crcs.fns = append(crcs.fns, fns...)
	return crcs
}

// Scan applies the selector query and scans the result into the given value.
func (crcs *CourseRecordCoachSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crcs.ctx, "Select")
	if err := crcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CourseRecordCoachQuery, *CourseRecordCoachSelect](ctx, crcs.CourseRecordCoachQuery, crcs, crcs.inters, v)
}

func (crcs *CourseRecordCoachSelect) sqlScan(ctx context.Context, root *CourseRecordCoachQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crcs.fns))
	for _, fn := range crcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
