// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"saas/pkg/db/ent/courserecordmember"
	"saas/pkg/db/ent/courserecordschedule"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CourseRecordMember is the model entity for the CourseRecordMember schema.
type CourseRecordMember struct {
	config `json:"-"`
	// ID of the ent.
	// primary key
	ID int64 `json:"id,omitempty"`
	// created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 状态[0:禁用;1:正常]
	Status int64 `json:"status,omitempty"`
	// 场馆id
	VenueID int64 `json:"venue_id,omitempty"`
	// 会员id
	MemberID int64 `json:"member_id,omitempty"`
	// 课程ID
	CourseRecordScheduleID int64 `json:"course_record_schedule_id,omitempty"`
	// 类型
	Type string `json:"type,omitempty"`
	// 开始时间
	StartTime time.Time `json:"start_time,omitempty"`
	// 开始时间
	EndTime time.Time `json:"end_time,omitempty"`
	// 上课签到时间
	SignStartTime time.Time `json:"sign_start_time,omitempty"`
	// 下课签到时间
	SignEndTime time.Time `json:"sign_end_time,omitempty"`
	// 会员购买课ID
	MemberProductID int64 `json:"member_product_id,omitempty"`
	// 会员购买课ID
	MemberProductItemID int64 `json:"member_product_item_id,omitempty"`
	// 教练ID
	CoachID int64 `json:"coach_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CourseRecordMemberQuery when eager-loading is set.
	Edges        CourseRecordMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CourseRecordMemberEdges holds the relations/edges for other nodes in the graph.
type CourseRecordMemberEdges struct {
	// Schedule holds the value of the schedule edge.
	Schedule *CourseRecordSchedule `json:"sch"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ScheduleOrErr returns the Schedule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseRecordMemberEdges) ScheduleOrErr() (*CourseRecordSchedule, error) {
	if e.loadedTypes[0] {
		if e.Schedule == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: courserecordschedule.Label}
		}
		return e.Schedule, nil
	}
	return nil, &NotLoadedError{edge: "schedule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CourseRecordMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case courserecordmember.FieldID, courserecordmember.FieldStatus, courserecordmember.FieldVenueID, courserecordmember.FieldMemberID, courserecordmember.FieldCourseRecordScheduleID, courserecordmember.FieldMemberProductID, courserecordmember.FieldMemberProductItemID, courserecordmember.FieldCoachID:
			values[i] = new(sql.NullInt64)
		case courserecordmember.FieldType:
			values[i] = new(sql.NullString)
		case courserecordmember.FieldCreatedAt, courserecordmember.FieldUpdatedAt, courserecordmember.FieldStartTime, courserecordmember.FieldEndTime, courserecordmember.FieldSignStartTime, courserecordmember.FieldSignEndTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CourseRecordMember fields.
func (crm *CourseRecordMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case courserecordmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			crm.ID = int64(value.Int64)
		case courserecordmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				crm.CreatedAt = value.Time
			}
		case courserecordmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				crm.UpdatedAt = value.Time
			}
		case courserecordmember.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				crm.Status = value.Int64
			}
		case courserecordmember.FieldVenueID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field venue_id", values[i])
			} else if value.Valid {
				crm.VenueID = value.Int64
			}
		case courserecordmember.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				crm.MemberID = value.Int64
			}
		case courserecordmember.FieldCourseRecordScheduleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field course_record_schedule_id", values[i])
			} else if value.Valid {
				crm.CourseRecordScheduleID = value.Int64
			}
		case courserecordmember.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				crm.Type = value.String
			}
		case courserecordmember.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				crm.StartTime = value.Time
			}
		case courserecordmember.FieldEndTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_time", values[i])
			} else if value.Valid {
				crm.EndTime = value.Time
			}
		case courserecordmember.FieldSignStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sign_start_time", values[i])
			} else if value.Valid {
				crm.SignStartTime = value.Time
			}
		case courserecordmember.FieldSignEndTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sign_end_time", values[i])
			} else if value.Valid {
				crm.SignEndTime = value.Time
			}
		case courserecordmember.FieldMemberProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_product_id", values[i])
			} else if value.Valid {
				crm.MemberProductID = value.Int64
			}
		case courserecordmember.FieldMemberProductItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_product_item_id", values[i])
			} else if value.Valid {
				crm.MemberProductItemID = value.Int64
			}
		case courserecordmember.FieldCoachID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field coach_id", values[i])
			} else if value.Valid {
				crm.CoachID = value.Int64
			}
		default:
			crm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CourseRecordMember.
// This includes values selected through modifiers, order, etc.
func (crm *CourseRecordMember) Value(name string) (ent.Value, error) {
	return crm.selectValues.Get(name)
}

// QuerySchedule queries the "schedule" edge of the CourseRecordMember entity.
func (crm *CourseRecordMember) QuerySchedule() *CourseRecordScheduleQuery {
	return NewCourseRecordMemberClient(crm.config).QuerySchedule(crm)
}

// Update returns a builder for updating this CourseRecordMember.
// Note that you need to call CourseRecordMember.Unwrap() before calling this method if this CourseRecordMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (crm *CourseRecordMember) Update() *CourseRecordMemberUpdateOne {
	return NewCourseRecordMemberClient(crm.config).UpdateOne(crm)
}

// Unwrap unwraps the CourseRecordMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (crm *CourseRecordMember) Unwrap() *CourseRecordMember {
	_tx, ok := crm.config.driver.(*txDriver)
	if !ok {
		panic("ent: CourseRecordMember is not a transactional entity")
	}
	crm.config.driver = _tx.drv
	return crm
}

// String implements the fmt.Stringer.
func (crm *CourseRecordMember) String() string {
	var builder strings.Builder
	builder.WriteString("CourseRecordMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", crm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(crm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(crm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", crm.Status))
	builder.WriteString(", ")
	builder.WriteString("venue_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.VenueID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.MemberID))
	builder.WriteString(", ")
	builder.WriteString("course_record_schedule_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.CourseRecordScheduleID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(crm.Type)
	builder.WriteString(", ")
	builder.WriteString("start_time=")
	builder.WriteString(crm.StartTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_time=")
	builder.WriteString(crm.EndTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sign_start_time=")
	builder.WriteString(crm.SignStartTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sign_end_time=")
	builder.WriteString(crm.SignEndTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("member_product_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.MemberProductID))
	builder.WriteString(", ")
	builder.WriteString("member_product_item_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.MemberProductItemID))
	builder.WriteString(", ")
	builder.WriteString("coach_id=")
	builder.WriteString(fmt.Sprintf("%v", crm.CoachID))
	builder.WriteByte(')')
	return builder.String()
}

// CourseRecordMembers is a parsable slice of CourseRecordMember.
type CourseRecordMembers []*CourseRecordMember
