// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
	"saas/biz/handler/mw"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxnotifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxpayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.LogMw(),
	}
}

func _wxrefundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxqrpayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxrefundnotifyMw() []app.HandlerFunc {
	// your code...
	return nil
}
