// Code generated by ent, DO NOT EDIT.

package ent

import (
	"system/biz/dal/mysql/ent/menu"
	"system/biz/dal/mysql/ent/menuparam"
	"system/biz/dal/mysql/ent/role"
	"system/biz/dal/mysql/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[2].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[1].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menuDescOrderNo is the schema descriptor for order_no field.
	menuDescOrderNo := menuFields[3].Descriptor()
	// menu.DefaultOrderNo holds the default value on creation for the order_no field.
	menu.DefaultOrderNo = menuDescOrderNo.Default.(int64)
	// menuDescDisabled is the schema descriptor for disabled field.
	menuDescDisabled := menuFields[4].Descriptor()
	// menu.DefaultDisabled holds the default value on creation for the disabled field.
	menu.DefaultDisabled = menuDescDisabled.Default.(int64)
	// menuDescIgnore is the schema descriptor for ignore field.
	menuDescIgnore := menuFields[5].Descriptor()
	// menu.DefaultIgnore holds the default value on creation for the ignore field.
	menu.DefaultIgnore = menuDescIgnore.Default.(bool)
	menuparamMixin := schema.MenuParam{}.Mixin()
	menuparamMixinFields0 := menuparamMixin[0].Fields()
	_ = menuparamMixinFields0
	menuparamFields := schema.MenuParam{}.Fields()
	_ = menuparamFields
	// menuparamDescCreatedAt is the schema descriptor for created_at field.
	menuparamDescCreatedAt := menuparamMixinFields0[1].Descriptor()
	// menuparam.DefaultCreatedAt holds the default value on creation for the created_at field.
	menuparam.DefaultCreatedAt = menuparamDescCreatedAt.Default.(func() time.Time)
	// menuparamDescUpdatedAt is the schema descriptor for updated_at field.
	menuparamDescUpdatedAt := menuparamMixinFields0[2].Descriptor()
	// menuparam.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menuparam.DefaultUpdatedAt = menuparamDescUpdatedAt.Default.(func() time.Time)
	// menuparam.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menuparam.UpdateDefaultUpdatedAt = menuparamDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleMixinFields1[0].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(int64)
	// roleDescDefaultRouter is the schema descriptor for default_router field.
	roleDescDefaultRouter := roleFields[2].Descriptor()
	// role.DefaultDefaultRouter holds the default value on creation for the default_router field.
	role.DefaultDefaultRouter = roleDescDefaultRouter.Default.(string)
	// roleDescRemark is the schema descriptor for remark field.
	roleDescRemark := roleFields[3].Descriptor()
	// role.DefaultRemark holds the default value on creation for the remark field.
	role.DefaultRemark = roleDescRemark.Default.(string)
	// roleDescOrderNo is the schema descriptor for order_no field.
	roleDescOrderNo := roleFields[4].Descriptor()
	// role.DefaultOrderNo holds the default value on creation for the order_no field.
	role.DefaultOrderNo = roleDescOrderNo.Default.(int64)
	// roleDescApis is the schema descriptor for apis field.
	roleDescApis := roleFields[5].Descriptor()
	// role.DefaultApis holds the default value on creation for the apis field.
	role.DefaultApis = roleDescApis.Default.([]int)
}
