Name: Kcersing Admin
IsProd: true
Host: 0.0.0.0
Port: 9039
Timeout: 30000

Captcha:
  KeyLong: 5
  ImgWidth: 240
  ImgHeight: 80

Auth:
  OAuthKey: OauthJf3z1n2xxx2cr1
  AccessSecret: D86VKDtsJf3z1nxxxxtsJf3z1n5
  AccessExpire: 259200 # seconds, 3 days

Redis:
  Host:
  Type: node

MySQL:
  #  Host: root:X3MeAGAmPSZp8A3H@tcp(121.40.98.240:3306)/saas?parseTime=True
  Host: master:2IPVvzUR*dsdrw57uzp40LUkUacK@tcp(pc-2ze5693uj6uav2nb7.rwlb.rds.aliyuncs.com:3306)/saas_y?parseTime=True
  Salt: YOUR_SALT

PostgreSQL:
  Host: postgresql://postgres:root@127.0.0.1/postgres
  Salt: YOUR_SALT

Casbin:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

# 支付平台信息配置
Payment:
  Alipay: # 以下配置文件为新沙箱环境配置
    appid:
    private_key:
    app_public_cert_content:
    alipay_root_cert_content:
    alipay_public_cert_content:
  Wechat:
    appid: wx1234567890
    mch_id:
    api_key:
    api_v3_key:
    cert_file_content:
    key_file_content:
    pkcs12_file_content:
    serial_no:
    notify_url:

Minio:
  EndPoint : 39.107.73.87:9000
  AccessKeyID : Yj123987
  SecretAccessKey : Yj987123
  UseSSL : false
  VideoBucketName : videobucket
  ImgBucketName : imagebucket
  Url : http://39.107.73.87:9000

Swagger:
  url : http://39.107.73.87:9039/swagger/doc.json