// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	admin_contest "saas/app/idl/biz/router/idl/contest"
	admin_admin "saas/app/idl/biz/router/idl/idl"
	contract_contract "saas/biz/router/contract/contract"

	admin_contract "saas/app/idl/biz/router/idl/contract"
	admin_dictionary "saas/app/idl/biz/router/idl/dictionary"
	admin_entry "saas/app/idl/biz/router/idl/entry"
	admin_logs "saas/app/idl/biz/router/idl/logs"
	admin_member "saas/app/idl/biz/router/idl/member"
	admin_menu "saas/app/idl/biz/router/idl/menu"
	admin_order "saas/app/idl/biz/router/idl/order"
	admin_product "saas/app/idl/biz/router/idl/product"
	admin_pub "saas/app/idl/biz/router/idl/pub"
	admin_role "saas/app/idl/biz/router/idl/role"
	admin_schedule "saas/app/idl/biz/router/idl/schedule"
	admin_sys "saas/app/idl/biz/router/idl/sys"
	admin_token "saas/app/idl/biz/router/idl/token"
	admin_user "saas/app/idl/biz/router/idl/user"
	admin_venue "saas/app/idl/biz/router/idl/venue"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	contract_contract.Register(r)

	admin_contest.Register(r)

	admin_entry.Register(r)

	admin_contract.Register(r)

	admin_schedule.Register(r)

	admin_sys.Register(r)

	admin_pub.Register(r)

	admin_member.Register(r)

	admin_order.Register(r)

	admin_venue.Register(r)

	admin_product.Register(r)

	admin_role.Register(r)

	admin_menu.Register(r)

	admin_logs.Register(r)

	admin_dictionary.Register(r)

	admin_admin.Register(r)

	admin_user.Register(r)

	admin_token.Register(r)
}
